language: python
python:
- 3.7
- 3.6
- 3.5
sudo: required
dist: xenial
install:
  - pip install -U tox-travis coveralls flake8
script:
  - tox
  - flake8 --exclude=.tox .eggs
after_success:
  - coveralls
